command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.address
  - "0.0.0.0"

env:
  # Full path to your specific GeoJSON file
  - name: GEOJSON_PATH
    value: "/Volumes/inv_weather_dev/forecasts/tropical_bi/tracks/model_tracks (1) (1).geojson"

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
